"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { useEffect } from "react"; // Import React's `useEffect`
import arrowcircle from "../../public/arrowcircle.svg";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Export `metadata` for server-side rendering
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Add scroll event listener to toggle the visibility of the scroll button
  useEffect(() => {
    const handleScroll = () => {
      const scrollBtn = document.querySelector(".scrollBtn");
      if (window.scrollY > 150) {
        scrollBtn?.classList.remove("hidden");
      } else {
        scrollBtn?.classList.add("hidden");
      }
    };

    window.addEventListener("scroll", handleScroll);

    // Cleanup event listener on component unmount
    return () => {
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <div className="fixed bottom-5 right-5 hidden scrollBtn z-50">
          <button
            className="p-3 rounded-full bg-black hover:bg-gray-700 shadow-lg"
            onClick={() =>
              window.scrollTo({
                top: 0,
                behavior: "smooth",
              })
            }
          >
            <Image src={arrowcircle} alt="Scroll to top" width={30} />
          </button>
        </div>
      </body>
    </html>
  );
}
